version: '3.8'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: manage_item_user
      POSTGRES_PASSWORD: manage_item_password
      POSTGRES_DB: manage_item
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
